<?php


$table = Db\Structure::table('shop_categories');
$table->primaryKey('id');
$table->column('name', db_varchar)->index();
$table->column('description', db_text);
$table->column('short_description', db_text);
$table->column('url_name', db_varchar, 100)->index();
$table->column('page_id', db_number)->index();
$table->column('meta_description', db_text);
$table->column('meta_keywords', db_text);
$table->column('category_id', db_number)->index();
$table->column('front_end_sort_order', db_number)->index();
$table->column('code', db_varchar, 50)->index();
$table->column('category_is_hidden', db_bool)->index();
$table->column('title', db_varchar);
$table->footprints();


$table = Db\Structure::table('shop_products');
$table->primaryKey('id');
$table->column('name', db_varchar)->index();
$table->column('description', db_text);
$table->column('short_description', db_text);
$table->column('url_name', db_varchar)->index();
$table->column('price', db_float, [21, 8])->index();
$table->column('sku', db_varchar, 100)->index()->unique();
$table->column('weight', db_float, [16, 3])->index();
$table->column('width', db_float, [16, 3])->index();
$table->column('height', db_float, [16, 3])->index();
$table->column('depth', db_float, [16, 3])->index();
$table->column('manufacturer_id', db_number)->index();
$table->column('meta_description', db_text);
$table->column('meta_keywords', db_text);
$table->column('on_sale', db_bool);
$table->column('enabled', db_bool)->index();
$table->column('track_inventory', db_bool)->index();
$table->column('in_stock', db_number)->index();
$table->column('hide_if_out_of_stock', db_bool)->index();
$table->column('stock_alert_threshold', db_number)->index();
$table->column('allow_pre_order', db_bool);
$table->column('page_id', db_number)->index();
$table->column('product_id', db_number)->index();
$table->column('grouped_option_desc', db_varchar);
$table->column('grouped', db_bool)->index();
$table->column('grouped_attribute_name', db_varchar, 100);
$table->column('tax_class_id', db_number)->index();
$table->column('product_type_id', db_number)->index();
$table->column('xml_data', db_text);
$table->column('tier_prices_per_customer', db_bool);
$table->column('tier_price_compiled', db_text);
$table->column('price_rules_compiled', db_text);
$table->column('grouped_sort_order', db_number);
$table->column('grouped_self_ghost_flag', db_bool);
$table->column('pt_description', db_text);
$table->column('expected_availability_date', db_date);
$table->column('enable_customer_group_filter', db_bool);
$table->column('disable_completely', db_bool)->index();
$table->column('enable_perproduct_shipping_cost', db_bool);
$table->column('perproduct_shipping_cost', db_text);
$table->column('price_rule_map_compiled', db_text);
$table->column('cost', db_float, [21, 8]);
$table->column('title', db_varchar);
$table->column('allow_negative_stock_values', db_bool);
$table->column('product_rating', db_float, [7, 5]);
$table->column('product_rating_all', db_float, [7, 5]);
$table->column('product_rating_review_num', db_number);
$table->column('product_rating_all_review_num', db_number);
$table->column('visibility_search', db_bool)->index();
$table->column('visibility_catalog', db_bool)->index();
$table->column('perproduct_shipping_cost_use_parent', db_bool);
$table->column('sale_price_or_discount', db_varchar, 50);
$table->column('price_index_compiled', db_text);
$table->column('total_in_stock', db_number);
$table->column('low_stock_threshold', db_number);
$table->column('shipping_hs_code', db_varchar);
$table->column('shipping_hs_code_extended', db_varchar);
$table->column('net_unit_code', db_varchar, 15);
$table->column('net_unit_quantity', db_float, [16, 3]);
$table->column('bulky_shipping_item', db_bool);
$table->footprints();

$table = Db\Structure::table('shop_products_categories');
$table->column('shop_product_id', db_number)->index();
$table->column('shop_category_id', db_number)->index();
$table->column('product_category_sort_order', db_number);
$table->addKey('product_category', ['shop_product_id', 'shop_category_id']);

$table = Db\Structure::table('shop_custom_attributes');
$table->primaryKey('id');
$table->column('product_id', db_number)->index();
$table->column('name', db_varchar)->index();
$table->column('attribute_values', db_varchar)->index();
$table->column('option_key', db_varchar, 35)->index();
$table->column('sort_order', db_number);

$table = Db\Structure::table('shop_extra_options');
$table->primaryKey('id');
$table->column('description', db_text);
$table->column('price', db_float, [21, 8]);
$table->column('product_id', db_number)->index();
$table->column('option_key', db_varchar, 35)->index();
$table->column('extra_option_sort_order', db_number);
$table->column('group_name', db_varchar)->index();
$table->column('option_in_set', db_bool)->index();
$table->column('weight', db_float, [16, 3]);
$table->column('width', db_float, [16, 3]);
$table->column('height', db_float, [16, 3]);
$table->column('depth', db_float, [16, 3]);

$table = Db\Structure::table('shop_related_products');
$table->column('master_product_id', db_number);
$table->column('related_product_id', db_number);
$table->addKey('PRIMARY', ['master_product_id', 'related_product_id'])->primary();

$table = Db\Structure::table('shop_custom_group');
$table->primaryKey('id');
$table->column('name', db_varchar, 100);
$table->column('code', db_varchar, 100)->index();

$table = Db\Structure::table('shop_products_customgroups');
$table->column('shop_product_id', db_number)->index();
$table->column('shop_custom_group_id', db_number)->index();
$table->addKey('PRIMARY', ['shop_product_id', 'shop_custom_group_id'])->primary();

$table = Db\Structure::table('shop_product_properties');
$table->primaryKey('id');
$table->column('product_id', db_number, 100)->index();
$table->column('property_set_property_id', db_number)->index();
$table->column('name', db_varchar)->index();
$table->column('value', db_varchar, 500);
$table->column('sort_order', db_number, 100);
$table->column('api_code', db_varchar, 50)->index();

$table = Db\Structure::table('shop_property_sets');
$table->primaryKey('id');
$table->column('name', db_varchar, 100);
$table->column('api_code', db_varchar, 50)->index();

$table = Db\Structure::table('shop_property_set_properties');
$table->primaryKey('id');
$table->column('property_set_id', db_number)->index();
$table->column('name', db_varchar);
$table->column('comment', db_varchar);
$table->column('value', db_varchar, 500);
$table->column('required', db_bool);
$table->column('validate', db_varchar, 10);
$table->column('select_values', db_text);
$table->column('api_code', db_varchar, 50)->index();
$table->column('sort_order', db_number);

$table = Db\Structure::table('shop_currency_settings');
$table->primaryKey('id');
$table->column('code', db_varchar, 10)->index();
$table->column('dec_point', db_varchar, 1);
$table->column('thousands_sep', db_varchar, 1);
$table->column('sign', db_varchar, 10);
$table->column('sign_before', db_bool);
$table->column('iso_4217_code', db_number)->index();
$table->column('name', db_varchar, 150);
$table->column('enabled', db_bool)->index();
//$table->column('rate_to_usd', db_float);
//$table->column('rate_adjust_percent', db_float, [6,3]);

$table = Db\Structure::table('shop_customers');
$table->primaryKey('id');
$table->column('first_name', db_varchar, 100);
$table->column('last_name', db_varchar, 100)->index();
$table->column('email', db_varchar, 50)->index();
$table->column('company', db_varchar, 100)->index();
$table->column('phone', db_varchar, 100);
$table->column('password', db_varchar, 50)->index();
$table->column('shipping_street_addr', db_varchar)->index();
$table->column('shipping_city', db_varchar, 100)->index();
$table->column('shipping_state_id', db_number);
$table->column('shipping_zip', db_varchar, 20);
$table->column('shipping_country_id', db_number);
$table->column('billing_street_addr', db_varchar)->index();
$table->column('billing_city', db_varchar, 100)->index();
$table->column('billing_state_id', db_number);
$table->column('billing_zip', db_varchar, 20);
$table->column('billing_country_id', db_number);
$table->column('guest', db_bool);
$table->column('shipping_first_name', db_varchar, 100);
$table->column('shipping_last_name', db_varchar, 100);
$table->column('shipping_phone', db_varchar, 100);
$table->column('shipping_company', db_varchar, 100);
$table->column('deleted_at', db_datetime);
$table->column('customer_group_id', db_number)->index();
$table->column('shipping_addr_is_business', db_bool);
$table->column('notes', db_text);
$table->column('password_restore_hash', db_varchar, 150);
$table->column('password_restore_time', db_datetime);
$table->column('preferred_currency_code', db_varchar, 10);
$table->footprints();

$table = Db\Structure::table('shop_countries');
$table->primaryKey('id');
$table->column('code', db_varchar, 2)->index();
$table->column('name', db_varchar, 100)->index();
$table->column('enabled', db_bool)->index();
$table->column('code_3', db_varchar, 3);
$table->column('code_iso_numeric', db_varchar, 10);
$table->column('enabled_in_backend', db_bool)->index();
$table->column('shipping_zone_id', db_number, 100)->index();
$table->column('disabled', db_bool)->index();

$table = Db\Structure::table('shop_states');
$table->primaryKey('id');
$table->column('country_id', db_number)->index();
$table->column('code', db_varchar, 50)->index();
$table->column('name', db_varchar, 100)->index();
$table->column('notify_recipients', db_bool);
$table->column('disabled', db_bool)->index();

$table = Db\Structure::table('shop_shipping_options');
$table->primaryKey('id');
$table->column('name', db_varchar, 255);
$table->column('description', db_text);
$table->column('class_name', db_varchar, 100);
$table->column('enabled', db_bool)->index();
$table->column('config_data', 'MEDIUMTEXT');
$table->column('taxable', db_bool);
$table->column('ls_api_code', db_varchar, 50)->index();
$table->column('handling_fee', db_float, [21, 8]);
$table->column('min_weight_allowed', db_float, [16, 3])->index();
$table->column('max_weight_allowed', db_float, [16, 3])->index();
$table->column('backend_enabled', db_bool)->index();

$table = Db\Structure::table('shop_customer_cart_items');
$table->primaryKey('id');
$table->column('customer_id', db_number)->index();
$table->column('product_id', db_number)->index();
$table->column('options', db_text);
$table->column('extras', db_text);
$table->column('quantity', db_number);
$table->column('postponed', db_bool);
$table->column('item_key', db_varchar, 32);
$table->column('cart_name', db_varchar, 15)->index();
$table->column('created_at', db_datetime)->index();
$table->column('bundle_master_cart_key', db_varchar, 32);
$table->column('bundle_offer_id', db_number);
$table->column('bundle_offer_item_id', db_number);

$table = Db\Structure::table('shop_tax_classes');
$table->primaryKey('id');
$table->column('name', db_varchar);
$table->column('description', db_text);
$table->column('code', db_varchar, 30)->index();
$table->column('rates', 'MEDIUMTEXT');
$table->column('is_default', db_bool);

$table = Db\Structure::table('shop_payment_methods');
$table->primaryKey('id');
$table->column('name', db_varchar);
$table->column('description', db_text);
$table->column('class_name', db_varchar, 100);
$table->column('enabled', db_bool)->index();
$table->column('config_data', db_text);
$table->column('receipt_page_id', db_number);
$table->column('ls_api_code', db_varchar, 50)->index();
$table->column('backend_enabled', db_bool)->index();

$table = Db\Structure::table('shop_payment_transactions');
$table->primaryKey('id');
$table->column('order_id', db_number)->index();
$table->column('transaction_id', db_varchar, 100)->index();
$table->column('transaction_status_name', db_varchar, 255);
$table->column('transaction_status_code', db_varchar, 100)->index();
$table->column('created_at', db_datetime)->index();
$table->column('created_user_id', db_number);
$table->column('payment_method_id', db_number)->index();
$table->column('user_note', db_text);
$table->column('fetched_from_gateway', db_bool);
$table->column('data_1', db_text);
$table->column('transaction_value', db_float, [21, 8])->index();
$table->column('transaction_value_currency_code', db_varchar, 4);
$table->column('transaction_complete', db_bool);
$table->column('transaction_refund', db_bool);
$table->column('transaction_void', db_bool);
$table->column('has_disputes', db_bool);
$table->column('liability_shifted', db_bool);
$table->column('settlement_value', db_float, [21, 8]);
$table->column('settlement_value_currency_code', db_varchar, 4);

$table = Db\Structure::table('shop_payment_transaction_disputes');
$table->primaryKey('id');
$table->column('api_transaction_id', db_varchar, 100)->index();
$table->column('case_id', db_varchar, 255);
$table->column('amount_disputed', db_float, [21, 8]);
$table->column('amount_lost', db_float, [21, 8]);
$table->column('status_description', db_varchar);
$table->column('reason_description', db_varchar);
$table->column('case_closed', db_bool);
$table->column('notes', db_text);
$table->column('gateway_api_data', db_text);
$table->column('shop_payment_transaction_id', db_number)->index();
$table->footprints();

$table = Db\Structure::table('shop_paymentmethods_countries');
$table->column('shop_payment_method_id', db_number)->index();
$table->column('shop_country_id', db_number)->index();
$table->addKey('PRIMARY', ['shop_payment_method_id', 'shop_country_id'])->primary();

$table = Db\Structure::table('shop_paymentmethods_customer_groups');
$table->column('shop_payment_method_id', db_number)->index();
$table->column('customer_group_id', db_number)->index();
$table->addKey('PRIMARY', ['shop_payment_method_id', 'customer_group_id'])->primary();


$table = Db\Structure::table('shop_orders');
$table->primaryKey('id');
$table->column('order_datetime', db_datetime)->index();
$table->column('shipping_method_id', db_number)->index();
$table->column('shipping_quote', db_float, [21, 8]);
$table->column('shipping_tax', db_float, [21, 8]);
$table->column('customer_id', db_number)->index();
$table->column('payment_method_id', db_number)->index();
$table->column('goods_tax', db_float, [21, 8]);
$table->column('billing_first_name', db_varchar, 100)->index();
$table->column('billing_last_name', db_varchar, 100)->index();
$table->column('billing_email', db_varchar, 50)->index();
$table->column('billing_phone', db_varchar, 100);
$table->column('billing_company', db_varchar, 100)->index();
$table->column('billing_street_addr', db_varchar);
$table->column('billing_city', db_varchar, 100);
$table->column('billing_state_id', db_number);
$table->column('billing_zip', db_varchar, 20);
$table->column('billing_country_id', db_number)->index();
$table->column('shipping_first_name', db_varchar, 100)->index();
$table->column('shipping_last_name', db_varchar, 100)->index();
$table->column('shipping_phone', db_varchar, 100);
$table->column('shipping_company', db_varchar, 100)->index();
$table->column('shipping_street_addr', db_varchar);
$table->column('shipping_city', db_varchar, 100);
$table->column('shipping_state_id', db_number);
$table->column('shipping_zip', db_varchar, 20);
$table->column('shipping_country_id', db_number)->index();
$table->column('status_id', db_number)->index();
$table->column('order_hash', db_varchar, 40)->index();
$table->column('total', db_float, [21, 8]);
$table->column('subtotal', db_float, [21, 8]);
$table->column('status_update_datetime', db_datetime);
$table->column('deleted_at', db_datetime)->index();
$table->column('payment_processed', db_datetime);
$table->column('customer_ip', db_varchar, 45)->index();
$table->column('customer_notes', db_text);
$table->column('shipping_sub_option', db_varchar);
$table->column('coupon_id', db_number)->index();
$table->column('discount', db_float, [21, 8]);
$table->column('tax_discount', db_float, [21, 8]);
$table->column('free_shipping', db_bool);
$table->column('shipping_discount', db_float, [21, 8]);
$table->column('manual_shipping_quote', db_float, [21, 8]);
$table->column('manual_shipping_discount', db_float, [21, 8]);
$table->column('auto_discount_price_eval', db_bool);
$table->column('shipping_tax_1', db_float, [21, 8]);
$table->column('shipping_tax_2', db_float, [21, 8]);
$table->column('shipping_tax_name_1', db_varchar, 30);
$table->column('shipping_tax_name_2', db_varchar, 30);
$table->column('sales_taxes', db_text);
$table->column('parent_order_id', db_number)->index();
$table->column('total_cost', db_float, [21, 8]);
$table->column('tax_exempt', db_number);
$table->column('automated_billing_fail', db_datetime)->index();
$table->column('automated_billing_success', db_datetime)->index();
$table->column('shipping_addr_is_business', db_bool);
$table->column('override_shipping_quote', db_bool);
$table->column('updated_at', db_datetime);
$table->column('order_date', db_date)->index();
$table->column('stock_updated', db_bool);
$table->column('currency_code', db_varchar, 4)->index();
$table->column('shop_currency_rate', db_float, [21, 8]);
$table->column('shop_currency_code', db_varchar, 4);
$table->column('locked', db_bool);


$table = Db\Structure::table('shop_order_statuses');
$table->primaryKey('id');
$table->column('code', db_varchar, 30)->index();
$table->column('name', db_varchar);
$table->column('color', db_varchar, 30);
$table->column('notify_customer', db_bool);
$table->column('enabled', db_bool);
$table->column('notify_recipient', db_bool);
$table->column('customer_message_template_id', db_number);
$table->column('admin_message_template_id', db_number);
$table->column('update_stock', db_bool);
$table->column('requires_payment_transaction_refunds', db_bool);
$table->column('order_lock_action', db_bool);
$table->column('notify_attach_document', db_varchar, 50);

$table = Db\Structure::table('shop_order_items');
$table->primaryKey('id');
$table->column('shop_product_id', db_number)->index();
$table->column('price', db_float, [21, 8]);
$table->column('shop_order_id', db_number)->index();
$table->column('quantity', db_number);
$table->column('options', db_text);
$table->column('extras', db_text);
$table->column('extras_price', db_float, [21, 8]);
$table->column('tax', db_float, [21, 8]);
$table->column('discount', db_float, [21, 8]);
$table->column('auto_discount_price_eval', db_bool);
$table->column('tax_2', db_float, [21, 8]);
$table->column('tax_name_1', db_varchar, 30);
$table->column('tax_name_2', db_varchar, 30);
$table->column('tax_discount_1', db_float, [21, 8]);
$table->column('tax_discount_2', db_float, [21, 8]);
$table->column('discount_tax_included', db_float, [21, 8]);
$table->column('price_tax_included', db_float, [21, 8]);
$table->column('cost', db_float, [21, 8]);
$table->column('bundle_master_order_item_id', db_number)->index();
$table->column('bundle_offer_id', db_number)->index();
$table->column('bundle_offer_name', db_varchar);
$table->column('option_matrix_record_id', db_number)->index();
$table->column('tax_class_id', db_number)->index();

$table = Db\Structure::table('shop_order_status_log_records');
$table->primaryKey('id');
$table->column('created_user_id', db_number);
$table->column('created_at', db_datetime);
$table->column('status_id', db_number)->index();
$table->column('comment', db_text);
$table->column('order_id', db_number)->index();

$table = Db\Structure::table('shop_order_payment_log');
$table->primaryKey('id');
$table->column('created_at', db_datetime)->index();
$table->column('is_successful', db_bool);
$table->column('message', db_varchar);
$table->column('request_data', db_text);
$table->column('response_data', db_text);
$table->column('raw_response_text', db_text);
$table->column('order_id', db_number)->index();
$table->column('payment_method_name', db_varchar);
$table->column('created_user_id', db_number);
$table->column('ccv_response_code', db_varchar, 20);
$table->column('ccv_response_text', db_varchar);
$table->column('avs_response_code', db_varchar, 20);
$table->column('avs_response_text', db_varchar);

$table = Db\Structure::table('shop_product_types');
$table->primaryKey('id');
$table->column('name', db_varchar);
$table->column('shipping', db_bool);
$table->column('files', db_bool);
$table->column('inventory', db_bool);
$table->column('is_default', db_bool);
$table->column('grouped', db_bool);
$table->column('options', db_bool);
$table->column('extras', db_bool);
$table->column('code', db_varchar, 50)->index();
$table->column('xml', db_bool);

$table = Db\Structure::table('shop_roles');
$table->primaryKey('id');
$table->column('name', db_varchar, 100);
$table->column('description', db_text);
$table->column('can_create_orders', db_bool);
$table->column('notified_on_out_of_stock', db_bool);

$table = Db\Structure::table('shop_status_transitions');
$table->primaryKey('id');
$table->column('from_state_id', db_number)->index();
$table->column('to_state_id', db_number)->index();
$table->column('role_id', db_number)->index();

$table = Db\Structure::table('shop_order_deleted_status');
$table->primaryKey('id');
$table->column('name', db_varchar, 100);
$table->column('code', db_varchar, 50);

$table = Db\Structure::table('shop_shippingoptions_countries');
$table->column('shop_country_id', db_number);
$table->column('shop_shipping_option_id', db_number);
$table->addKey('PRIMARY', ['shop_country_id', 'shop_shipping_option_id'])->primary();

$table = Db\Structure::table('shop_shipping_params');
$table->primaryKey('id');
$table->column('country_id', db_number);
$table->column('state_id', db_number);
$table->column('zip_code', db_varchar, 30);
$table->column('city', db_varchar);
$table->column('weight_unit', db_varchar, 10);
$table->column('dimension_unit', db_varchar, 10);
$table->column('default_shipping_country_id', db_number);
$table->column('default_shipping_state_id', db_number);
$table->column('default_shipping_city', db_varchar, 100);
$table->column('default_shipping_zip', db_varchar, 30);
$table->column('display_shipping_service_errors', db_bool);
$table->column('sender_first_name', db_varchar);
$table->column('sender_last_name', db_varchar);
$table->column('street_addr', db_varchar);
$table->column('sender_company', db_varchar);
$table->column('sender_phone', db_varchar, 100);
$table->column('enable_hs_codes', db_bool);

$table = Db\Structure::table('shop_currency_exchange_rates');
$table->primaryKey('id');
$table->column('created_at', db_datetime);
$table->column('from_currency', db_varchar, 3);
$table->column('to_currency', db_varchar, 3);
$table->column('rate', db_float, [21, 8]);
$table->addKey('from_currency_to_currency', ['from_currency', 'to_currency']);

$table = Db\Structure::table('shop_currency_converter_params');
$table->primaryKey('id');
$table->column('class_name', db_varchar, 100);
$table->column('refresh_interval', db_number);
$table->column('config_data', db_text);
$table->column('enable_cron_updates', db_bool);

$table = Db\Structure::table('shop_customer_groups');
$table->primaryKey('id');
$table->column('code', db_varchar, 50)->index();
$table->column('name', db_varchar, 100);
$table->column('description', db_text);
$table->column('disable_tax_included', db_bool);
$table->column('tax_exempt', db_bool);

$table = Db\Structure::table('shop_tier_prices');
$table->primaryKey('id');
$table->column('product_id', db_number)->index();
$table->column('customer_group_id', db_number)->index();
$table->column('quantity', db_number);
$table->column('price', db_float, [21, 8]);
$table->column('timestamp_created', 'TIMESTAMP');

$table = Db\Structure::table('shop_catalog_rules');
$table->primaryKey('id');
$table->column('date_start', db_datetime)->index();
$table->column('date_end', db_datetime)->index();
$table->column('name', db_varchar);
$table->column('description', db_text);
$table->column('active', db_bool);
$table->column('sort_order', db_number);
$table->column('terminating', db_bool);
$table->column('action_class_name', db_varchar, 100);
$table->column('action_xml_data', db_text);
$table->column('parameters_serialized', db_text);

$table = Db\Structure::table('shop_catalog_rules_customer_groups');
$table->column('shop_catalog_rule_id', db_number);
$table->column('shop_customer_group_id', db_number);
$table->addKey('PRIMARY', ['shop_catalog_rule_id', 'shop_customer_group_id'])->primary();

$table = Db\Structure::table('shop_price_rule_conditions');
$table->primaryKey('id');
$table->column('rule_parent_id', db_number)->index();
$table->column('class_name', db_varchar, 100);
$table->column('xml_data', db_text);
$table->column('rule_host_id', db_number);
$table->column('host_rule_set', db_varchar, 100);
$table->column('created_at', db_datetime);
$table->column('created_user_id', db_number);
$table->column('parameters_serialized', db_text);
$table->column('condition_control_type', db_varchar, 100);
$table->addKey('rule_host_set', ['rule_host_id', 'host_rule_set']);
